name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or any version you prefer

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Move images folder
        run: |
          $buildOutputFolder = "dist"
          $publishFolder = Join-Path $buildOutputFolder "public"
          $imagesFolder = Join-Path $buildOutputFolder "images"

          if (-not (Test-Path $publishFolder)) {
              New-Item -ItemType Directory -Path $publishFolder
          }

          if (Test-Path $imagesFolder) {
              Move-Item -Path $imagesFolder -Destination $publishFolder
          } else {
              Write-Host "The 'images' folder does not exist in the specified location."
        shell: pwsh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/public

  # Additional jobs (if any) go here
